# site setting
title: seven
baseurl: /seven
favicon: favicon.png
banner-image: banner1.jpg 
exclude: ['README.md']
permalink: pretty #to remove .html
gems:
  - jekyll-seo-tag
  - jekyll-sitemap

#Gems
gems: [jekyll-paginate]
paginate: 60
paginate_path: "/blog/page:num/"
  
include: ['_pages']

