- product-background-image: footbanner.jpeg
  product-heading: Our product
  product-image-one: product1.png
  product-subtitle-one: Virat Series
  product-image-two: product2.jpg
  product-subtitle-two: Congo series
  product-image-four: product4.jpg
  product-subtitle-four: Jumbo series
  product-image-three: product1.jpg
  product-subtitle-three: Jumbo series