- product-background-image: footbanner.jpeg
  product-heading: Our product
  product-image-one: product2.png
  product-subtitle-one: Virat Series
  product-image-two: product2.jpg
  product-subtitle-two: Congo series
  product-image-three: product3.jpg
  product-subtitle-three: Jumbo series