- product-image-one: product.jpg
  product-subtitle-one: UPVC Plumbing Pipes

  product-image-two: product.jpg
  product-subtitle-two: UPVC Submersible Column Pipes

  product-image-three: product.jpg
  product-subtitle-three: Water Tanks